### ISSUE TITLE
[Feature] 增加一个搜索栏

### ISSUE THREAD

**Issue by happy-game** [syt2/zotero-addons#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
希望能在最下面添加一个搜索框。

**Why do you need this feature?**
目前插件没有搜索栏，只能通过排序之后一个一个找自己想要的插件，这样很不方便。如果已经知道插件的名字，使用搜索去寻找会快很多。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by syt2** [comment]
1.7.0 底部添加了版搜索框，后面有时间再优化下搜索算法
