### ISSUE TITLE
[Feature] 功能建议：希望能自定义插件安装目录

### ISSUE THREAD

**Issue by bubble-coder** [syt2/zotero-addons#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by syt2** [comment]
感觉这个需求不多见，不打算在该插件内实现此功能。
